# COS60008 Introduction to data science
## Assignment 3 - Final Project, 2023, Semester 1
## Student Details: 
* Name: Kritika.
* Student id: 104361002
* Email: mailto:104361002@student.swin.edu.au
* Submission date: 28/06/2023
* Tutelab class: 3:30 - 5:30pm Thursday

## Task 1: Data loading and preparation

In [3]:
# loading the datafiles and importing packages
import pandas as pd
import numpy as np

In [4]:
#first datafile
data_1_env = pd.read_csv('data_1_env.csv')
# as the table was provided for description of columns, required data cleaning and conversion is done accordingly.

#converting the temperature to celsius
data_1_env['Avg Min Temp *C'] = (data_1_env['Avg Min Temp *F'] - 32) * 5 / 9

# renaming the column
data_1_env = data_1_env.rename(columns={'Avg Min Temp *C': 'Avg Min Temp °C'})

# removing the Fahrenheit column as we already converted the values
data_1_env = data_1_env.drop(columns=['Avg Min Temp *F'])
data_1_env

,Year,Location,Yr Rain inches,Heat Wave,Dry Spell,Cold Wave,Wet Spell,Avg Min Temp °C
0,1980,East Carlburgh,34.6579,0,N,Y,N,19.9
1,1980,Ramirezview,31.2599,N,N,Y,N,23.4
2,1980,East Carloston,42.9000,N,N,N,N,20.7
3,1981,East Carlburgh,31.0839,N,N,Y,N,20.1
4,1981,Ramirezview,26.8536,N,N,Y,N,22.9
5,1981,East Carloston,50.5563,N,N,N,N,20.9
6,1982,East Carlburgh,29.3272,N,N,Y,N,20.3
7,1982,Ramirezview,22.7024,N,N,Y,N,23.1
8,1982,East Carloston,50.7323,N,N,N,N,20.9
9,1983,East Carlburgh,34.0803,N,N,1,N,19.9
10,1983,Ramirezview,23.3063,N,N,Y,N,23.1
11,1983,East Carloston,54.0457,N,N,N,N,20.8
12,1984,East Carlburgh,35.4276,N,N,Y,N,20.4
13,1984,Ramirezview,24.4768,N,N,Y,N,23.2
14,1984,East Carloston,50.0366,N,N,N,N,21.4
15,1985,Ramirezview,23.4197,N,N,Y,N,23.1
16,1985,East Carloston,57.4146,N,N,N,N,21.1
17,1985,East Carlburgh,42.7390,N,N,Y,N,20.5
18,1986,East Carloston,51.4418,N,N,N,N,21.3
19,1986,East Carlburgh,34.7469,N,N,Y,N,20.1
20,1986,Ramirezview,25.0606,N,N,Y,N,23.3
21,1987,East Carloston,57.3603,N,N,N,N,21.5
22,1987,East Carlburgh,40.6768,N,0,Y,N,20.5
23,1987,Ramirezview,27.3106,N,N,Y,N,23.1
24,1988,East Carloston,51.4414,N,N,N,N,21.2
25,1988,East Carlburgh,37.1795,N,N,N,no,20.3
26,1988,Ramirezview,31.0650,N,N,Y,N,23.3
27,1989,East Carloston,56.3067,N,N,N,N,21.5
28,1989,East Carlburgh,38.2193,N,N,Y,N,20.5
29,1989,Ramirezview,28.6083,N,N,Y,N,23.6
30,1990,East Carloston,53.6985,N,N,N,N,21.3
31,1990,Ramirezview,30.4669,N,N,Y,N,23.6
32,1990,East Carlburgh,36.4063,N,N,Y,N,20.5
33,1991,Ramirezview,27.7689,N,N,N,N,23.4
34,1991,East Carloston,62.3130,N,N,N,N,21.6
35,1991,East Carlburgh,44.8481,N,N,N,N,20.7
36,1992,Ramirezview,31.7051,N,N,N,N,23.7
37,1992,East Carloston,51.8481,N,N,N,N,21.6
38,1992,East Carlburgh,46.8713,N,N,N,N,20.9
39,1993,Ramirezview,32.7232,N,N,N,N,23.9
40,1993,East Carloston,56.1697,N,N,N,N,21.6
41,1993,East Carlburgh,43.4441,N,N,N,N,20.8
42,1994,Ramirezview,32.3729,Y,Y,N,N,23.9
43,1994,East Carloston,60.7461,N,N,N,N,21.9
44,1994,East Carlburgh,47.6378,N,N,N,N,20.8
45,1995,Ramirezview,28.1520,N,N,N,N,23.7
46,1995,East Carloston,61.3772,N,N,N,N,21.5
47,1995,East Carlburgh,45.1465,N,N,N,0,21.2
48,1996,East Carlburgh,44.4197,N,N,N,0,21.0
49,1996,Ramirezview,30.7465,N,Y,N,N,24.0
50,1996,East Carloston,61.4701,N,N,N,N,21.8
51,1997,East Carlburgh,47.6894,N,N,N,Y,21.0
52,1997,Ramirezview,33.7827,N,N,N,N,23.9
53,1997,East Carloston,67.1839,N,N,N,Y,21.8

In [5]:
#converting rainfall from inches to mm
data_1_env['Yr Rain mm'] = data_1_env['Yr Rain inches'] * 25.4

# renaming the column
data_1_env = data_1_env.rename(columns={'Yr Rain mm': 'Yr Rain mm'})

# dropping the inches column as we already converted the values
data_1_env = data_1_env.drop(columns=['Yr Rain inches'])
print(data_1_env)

    Year        Location Heat Wave Dry Spell Cold Wave Wet Spell  \
0   1980  East Carlburgh         0         N         Y         N
1   1980     Ramirezview         N         N         Y         N
2   1980  East Carloston         N         N         N         N
3   1981  East Carlburgh         N         N         Y         N
4   1981     Ramirezview         N         N         Y         N
5   1981  East Carloston         N         N         N         N
6   1982  East Carlburgh         N         N         Y         N
7   1982     Ramirezview         N         N         Y         N
8   1982  East Carloston         N         N         N         N
9   1983  East Carlburgh         N         N         1         N
10  1983     Ramirezview         N         N         Y         N
11  1983  East Carloston         N         N         N         N
12  1984  East Carlburgh         N         N         Y         N
13  1984     Ramirezview         N         N         Y         N
14  1984  East Carloston         N         N         N         N
15  1985     Ramirezview         N         N         Y         N
16  1985  East Carloston         N         N         N         N
17  1985  East Carlburgh         N         N         Y         N
18  1986  East Carloston         N         N         N         N
19  1986  East Carlburgh         N         N         Y         N
20  1986     Ramirezview         N         N         Y         N
21  1987  East Carloston         N         N         N         N
22  1987  East Carlburgh         N         0         Y         N
23  1987     Ramirezview         N         N         Y         N
24  1988  East Carloston         N         N         N         N
25  1988  East Carlburgh         N         N         N        no
26  1988     Ramirezview         N         N         Y         N
27  1989  East Carloston         N         N         N         N
28  1989  East Carlburgh         N         N         Y         N
29  1989     Ramirezview         N         N         Y         N
30  1990  East Carloston         N         N         N         N
31  1990     Ramirezview         N         N         Y         N
32  1990  East Carlburgh         N         N         Y         N
33  1991     Ramirezview         N         N         N         N
34  1991  East Carloston         N         N         N         N
35  1991  East Carlburgh         N         N         N         N
36  1992     Ramirezview         N         N         N         N
37  1992  East Carloston         N         N         N         N
38  1992  East Carlburgh         N         N         N         N
39  1993     Ramirezview         N         N         N         N
40  1993  East Carloston         N         N         N         N
41  1993  East Carlburgh         N         N         N         N
42  1994     Ramirezview         Y         Y         N         N
43  1994  East Carloston         N         N         N         N
44  1994  East Carlburgh         N         N         N         N
45  1995     Ramirezview         N         N         N         N
46  1995  East Carloston         N         N         N         N
47  1995  East Carlburgh         N         N         N         0
48  1996  East Carlburgh         N         N         N         0
49  1996     Ramirezview         N         Y         N         N
50  1996  East Carloston         N         N         N         N
51  1997  East Carlburgh         N         N         N         Y
52  1997     Ramirezview         N         N         N         N
53  1997  East Carloston         N         N         N         Y

    Avg Min Temp °C  Yr Rain mm
0              19.9   880.31066
1              23.4   794.00146
2              20.7  1089.66000
3              20.1   789.53106
4              22.9   682.08144
5              20.9  1284.13002
6              20.3   744.91088
7              23.1   576.64096
8              20.9  1288.60042
9              19.9   865.63962
10             23.1   591.98002
11             20.8  1372.76078
12             20.4   899.86104
13             23.2   621.71072
14             21.4  1270.92964
15             23.1   594.86038
16             21.1  1458.33084
17             20.5  1085.57060
18             21.3  1306.62172
19             20.1   882.57126
20             23.3   636.53924
21             21.5  1456.95162
22             20.5  1033.19072
23             23.1   693.68924
24             21.2  1306.61156
25             20.3   944.35930
26             23.3   789.05100
27             21.5  1430.19018
28             20.5   970.77022
29             23.6   726.65082
30             21.3  1363.94190
31             23.6   773.85926
32             20.5   924.72002
33             23.4   705.33006
34             21.6  1582.75020
35             20.7  1139.14174
36             23.7   805.30954
37             21.6  1316.94174
38             20.9  1190.53102
39             23.9   831.16928
40             21.6  1426.71038
41             20.8  1103.48014
42             23.9   822.27166
43             21.9  1542.95094
44             20.8  1210.00012
45             23.7   715.06080
46             21.5  1558.98088
47             21.2  1146.72110
48             21.0  1128.26038
49             24.0   780.96110
50             21.8  1561.34054
51             21.0  1211.31076
52             23.9   858.08058
53             21.8  1706.47106

In [6]:
#checking for missing values
missing_values = data_1_env.isnull().sum()
print(missing_values)

data_1_env = data_1_env.dropna()

# checking the missing values are handled or not
missing_values_after = data_1_env.isnull().sum()
print(missing_values_after)
#no missing values

Year               0
Location           0
Heat Wave          0
Dry Spell          0
Cold Wave          0
Wet Spell          0
Avg Min Temp °C    0
Yr Rain mm         0
dtype: int64
Year               0
Location           0
Heat Wave          0
Dry Spell          0
Cold Wave          0
Wet Spell          0
Avg Min Temp °C    0
Yr Rain mm         0
dtype: int64

In [7]:
# checking for duplicate rows
duplicate_rows = data_1_env[data_1_env.duplicated()]
print(duplicate_rows)

# removing the duplicate rows
data_1_env = data_1_env.drop_duplicates()

# checking the duplicate rows are handled
duplicate_rows_check = data_1_env[data_1_env.duplicated()]
print(duplicate_rows_check)

Empty DataFrame
Columns: [Year, Location, Heat Wave, Dry Spell, Cold Wave, Wet Spell, Avg Min Temp °C, Yr Rain mm]
Index: []
Empty DataFrame
Columns: [Year, Location, Heat Wave, Dry Spell, Cold Wave, Wet Spell, Avg Min Temp °C, Yr Rain mm]
Index: []

In [8]:
invalid_rows = data_1_env[(data_1_env['Heat Wave'] != 'Y') & (data_1_env['Heat Wave'] != 'N')]
print(invalid_rows)
#the above method was used to find rows not matching the criteria

   Year        Location Heat Wave Dry Spell Cold Wave Wet Spell  \
0  1980  East Carlburgh         0         N         Y         N

   Avg Min Temp °C  Yr Rain mm
0             19.9   880.31066

In [9]:
#checking the values in column are Y/N as described in the provided table

data_1_env['Heat Wave'] = data_1_env['Heat Wave'].replace({'1': 'Y', '0': 'N'})

# checking if all values in the column are either 'Y' or 'N'
if set(data_1_env['Heat Wave'].unique()) == {'Y', 'N'}:
    print("Yes all values are either 'Y' or 'N' in 'Heat Wave'.")
else:
    print("There are still invalid values in the 'Heat Wave'.")

Yes all values are either 'Y' or 'N' in 'Heat Wave'.

In [10]:
invalid_rows = data_1_env[(data_1_env['Dry Spell'] != 'Y') & (data_1_env['Dry Spell'] != 'N')]
print(invalid_rows)
#the above method was used to find rows not matching the criteria

    Year        Location Heat Wave Dry Spell Cold Wave Wet Spell  \
22  1987  East Carlburgh         N         0         Y         N

    Avg Min Temp °C  Yr Rain mm
22             20.5  1033.19072

In [11]:
data_1_env['Dry Spell'] = data_1_env['Dry Spell'].replace({'1': 'Y', '0': 'N'})

# checking all values in the column are either 'Y' or 'N'
if set(data_1_env['Dry Spell'].unique()) == {'Y', 'N'}:
    print("All values in the column are either 'Y' or 'N'.")
else:
    print("There are still invalid values in the column.")

All values in the column are either 'Y' or 'N'.

In [12]:
invalid_rows = data_1_env[(data_1_env['Cold Wave'] != 'Y') & (data_1_env['Cold Wave'] != 'N')]
print(invalid_rows)
#the above method was used to find rows not matching the criteria

   Year        Location Heat Wave Dry Spell Cold Wave Wet Spell  \
9  1983  East Carlburgh         N         N         1         N

   Avg Min Temp °C  Yr Rain mm
9             19.9   865.63962

In [13]:
data_1_env['Cold Wave'] = data_1_env['Cold Wave'].replace({'1': 'Y', '0': 'N'})

# checking all values in the column are either 'Y' or 'N'
if set(data_1_env['Cold Wave'].unique()) == {'Y', 'N'}:
    print("All values in the column are either 'Y' or 'N'.")
else:
    print("There are still invalid values in the column.")

All values in the column are either 'Y' or 'N'.

In [12]:
invalid_rows = data_1_env[(data_1_env['Wet Spell'] != 'Y') & (data_1_env['Wet Spell'] != 'N')]
print(invalid_rows)
#the above method was used to find rows not matching the criteria

    Year        Location Heat Wave Dry Spell Cold Wave Wet Spell  \
25  1988  East Carlburgh         N         N         N        no
47  1995  East Carlburgh         N         N         N         0
48  1996  East Carlburgh         N         N         N         0

    Avg Min Temp °C  Yr Rain mm
25             20.3   944.35930
47             21.2  1146.72110
48             21.0  1128.26038

In [14]:
data_1_env['Wet Spell'] = data_1_env['Wet Spell'].replace({'1': 'Y', '0': 'N','no':'N'})

# checking all values in the column are either 'Y' or 'N'
if set(data_1_env['Wet Spell'].unique()) == {'Y', 'N'}:
    print("All values in the column are either 'Y' or 'N'.")
else:
    print("There are still invalid values in the column.")

All values in the column are either 'Y' or 'N'.

In [15]:
data_1_env

,Year,Location,Heat Wave,Dry Spell,Cold Wave,Wet Spell,Avg Min Temp °C,Yr Rain mm
0,1980,East Carlburgh,N,N,Y,N,19.9,880.31066
1,1980,Ramirezview,N,N,Y,N,23.4,794.00146
2,1980,East Carloston,N,N,N,N,20.7,1089.66000
3,1981,East Carlburgh,N,N,Y,N,20.1,789.53106
4,1981,Ramirezview,N,N,Y,N,22.9,682.08144
5,1981,East Carloston,N,N,N,N,20.9,1284.13002
6,1982,East Carlburgh,N,N,Y,N,20.3,744.91088
7,1982,Ramirezview,N,N,Y,N,23.1,576.64096
8,1982,East Carloston,N,N,N,N,20.9,1288.60042
9,1983,East Carlburgh,N,N,Y,N,19.9,865.63962
10,1983,Ramirezview,N,N,Y,N,23.1,591.98002
11,1983,East Carloston,N,N,N,N,20.8,1372.76078
12,1984,East Carlburgh,N,N,Y,N,20.4,899.86104
13,1984,Ramirezview,N,N,Y,N,23.2,621.71072
14,1984,East Carloston,N,N,N,N,21.4,1270.92964
15,1985,Ramirezview,N,N,Y,N,23.1,594.86038
16,1985,East Carloston,N,N,N,N,21.1,1458.33084
17,1985,East Carlburgh,N,N,Y,N,20.5,1085.57060
18,1986,East Carloston,N,N,N,N,21.3,1306.62172
19,1986,East Carlburgh,N,N,Y,N,20.1,882.57126
20,1986,Ramirezview,N,N,Y,N,23.3,636.53924
21,1987,East Carloston,N,N,N,N,21.5,1456.95162
22,1987,East Carlburgh,N,N,Y,N,20.5,1033.19072
23,1987,Ramirezview,N,N,Y,N,23.1,693.68924
24,1988,East Carloston,N,N,N,N,21.2,1306.61156
25,1988,East Carlburgh,N,N,N,N,20.3,944.35930
26,1988,Ramirezview,N,N,Y,N,23.3,789.05100
27,1989,East Carloston,N,N,N,N,21.5,1430.19018
28,1989,East Carlburgh,N,N,Y,N,20.5,970.77022
29,1989,Ramirezview,N,N,Y,N,23.6,726.65082
30,1990,East Carloston,N,N,N,N,21.3,1363.94190
31,1990,Ramirezview,N,N,Y,N,23.6,773.85926
32,1990,East Carlburgh,N,N,Y,N,20.5,924.72002
33,1991,Ramirezview,N,N,N,N,23.4,705.33006
34,1991,East Carloston,N,N,N,N,21.6,1582.75020
35,1991,East Carlburgh,N,N,N,N,20.7,1139.14174
36,1992,Ramirezview,N,N,N,N,23.7,805.30954
37,1992,East Carloston,N,N,N,N,21.6,1316.94174
38,1992,East Carlburgh,N,N,N,N,20.9,1190.53102
39,1993,Ramirezview,N,N,N,N,23.9,831.16928
40,1993,East Carloston,N,N,N,N,21.6,1426.71038
41,1993,East Carlburgh,N,N,N,N,20.8,1103.48014
42,1994,Ramirezview,Y,Y,N,N,23.9,822.27166
43,1994,East Carloston,N,N,N,N,21.9,1542.95094
44,1994,East Carlburgh,N,N,N,N,20.8,1210.00012
45,1995,Ramirezview,N,N,N,N,23.7,715.06080
46,1995,East Carloston,N,N,N,N,21.5,1558.98088
47,1995,East Carlburgh,N,N,N,N,21.2,1146.72110
48,1996,East Carlburgh,N,N,N,N,21.0,1128.26038
49,1996,Ramirezview,N,Y,N,N,24.0,780.96110
50,1996,East Carloston,N,N,N,N,21.8,1561.34054
51,1997,East Carlburgh,N,N,N,Y,21.0,1211.31076
52,1997,Ramirezview,N,N,N,N,23.9,858.08058
53,1997,East Carloston,N,N,N,Y,21.8,1706.47106

In [16]:
#moving on to second datafile:
data_2_env = pd.read_csv('data_2_env.csv')
data_2_env

,Year,Location,Avg Min Temp *C,Yr Rain mm,Heat Wave,Dry Spell,Cold Wave,Wet Spell
0,1998,East Carlburgh,21.2,1209.48,N,N,N,N
1,1998,Ramirezview,23.7,827.86,N,N,N,N
2,1998,East Carloston,21.8,1448.54,N,N,N,N
3,1999,Ramirezview,23.8,900.54,N,No,N,Y
4,1999,East Carloston,21.7,1589.79,N,N,N,Y
...,...,...,...,...,...,...,...,...
61,2018,East Carlburgh,21.9,1695.80,Y,N,N,Y
62,2018,East Carloston,22.6,1842.32,N,N,N,Y
63,2019,East Carloston,23.2,1904.86,N,N,N,Y
64,2019,East Carlburgh,22.1,1570.74,Y,N,N,Y
65,2019,Ramirezview,24.9,1166.17,Y,N,N,Y

In [17]:
#checking for missing values
missing_values = data_2_env.isnull().sum()
print(missing_values)

data_2_env = data_2_env.dropna()

# check if the missing values have been handled
missing_values_after = data_2_env.isnull().sum()
print(missing_values_after)
#no missing values

Year               0
Location           0
Avg Min Temp *C    0
Yr Rain mm         0
Heat Wave          0
Dry Spell          0
Cold Wave          0
Wet Spell          0
dtype: int64
Year               0
Location           0
Avg Min Temp *C    0
Yr Rain mm         0
Heat Wave          0
Dry Spell          0
Cold Wave          0
Wet Spell          0
dtype: int64

In [18]:
# checking for duplicate rows
duplicate_rows = data_2_env[data_2_env.duplicated()]
print(duplicate_rows)

# handling duplicate rows
data_2_env = data_2_env.drop_duplicates()

# check if duplicate rows have been handled
duplicate_rows_now = data_2_env[data_2_env.duplicated()]
print(duplicate_rows_now)

Empty DataFrame
Columns: [Year, Location, Avg Min Temp *C, Yr Rain mm, Heat Wave, Dry Spell, Cold Wave, Wet Spell]
Index: []
Empty DataFrame
Columns: [Year, Location, Avg Min Temp *C, Yr Rain mm, Heat Wave, Dry Spell, Cold Wave, Wet Spell]
Index: []

In [19]:
# check which rows dont have match the criteria
invalid_rows = data_2_env[(data_2_env['Heat Wave'] != 'Y') & (data_2_env['Heat Wave'] != 'N')]
print(invalid_rows)

#replacing with 'Y' or 'N' accordingly
data_2_env['Heat Wave'] = data_2_env['Heat Wave'].replace({'Yes': 'Y', '0': 'N','n':'N','No':'N','yes':'Y'})

# check all values in the column are either 'Y' or 'N'
if set(data_2_env['Heat Wave'].unique()) == {'Y', 'N'}:
    print("All values in the column are either 'Y' or 'N'.")
else:
    print("There are still invalid values in the column.")

    Year        Location  Avg Min Temp *C  Yr Rain mm Heat Wave Dry Spell  \
5   1999  East Carlburgh             21.3     1118.52       Yes         Y
13  2002  East Carloston             22.1     1379.01         n         Y
37  2010  East Carloston             22.4     1735.02        No         N
39  2011     Ramirezview             24.6     1129.73       yes         N
58  2017  East Carloston             23.0     1761.59         n         N

   Cold Wave Wet Spell
5          N         N
13         N         N
37         N         Y
39         N         Y
58         N         Y
All values in the column are either 'Y' or 'N'.

In [20]:
invalid_rows = data_2_env[(data_2_env['Dry Spell'] != 'Y') & (data_2_env['Dry Spell'] != 'N')]
print(invalid_rows)

#replacing with 'Y' or 'N' accordingly
data_2_env['Dry Spell'] = data_2_env['Dry Spell'].replace({'0': 'N','No':'N','no':'N'})

# check if all values in the column are either 'Y' or 'N'
if set(data_2_env['Dry Spell'].unique()) == {'Y', 'N'}:
    print("All values in the column are either 'Y' or 'N'.")
else:
    print("There are still invalid values in the column.")

    Year        Location  Avg Min Temp *C  Yr Rain mm Heat Wave Dry Spell  \
3   1999     Ramirezview             23.8      900.54         N        No
27  2007  East Carlburgh             21.6     1444.12         Y        No
42  2012  East Carlburgh             21.7     1533.48         Y        no
60  2018     Ramirezview             25.1     1194.61         Y         0

   Cold Wave Wet Spell
3          N         Y
27         N         Y
42         N         Y
60         N         Y
All values in the column are either 'Y' or 'N'.

In [21]:
invalid_rows = data_2_env[(data_2_env['Cold Wave'] != 'Y') & (data_2_env['Cold Wave'] != 'N')]
print(invalid_rows)

    Year        Location  Avg Min Temp *C  Yr Rain mm Heat Wave Dry Spell  \
25  2006     Ramirezview             24.4      973.86         Y         N
49  2014  East Carloston             22.2     2067.68         N         N

   Cold Wave Wet Spell
25        No         Y
49        no         Y

In [22]:
#replacing with 'Y' or 'N'
data_2_env['Cold Wave'] = data_2_env['Cold Wave'].replace({'No':'N','no':'N'})

In [23]:
# checking again for the 'Cold Wave' column
invalid_rows = data_2_env[(data_2_env['Cold Wave'] != 'Y') & (data_2_env['Cold Wave'] != 'N')]
print(invalid_rows)

Empty DataFrame
Columns: [Year, Location, Avg Min Temp *C, Yr Rain mm, Heat Wave, Dry Spell, Cold Wave, Wet Spell]
Index: []

In [24]:

invalid_rows = data_2_env[(data_2_env['Wet Spell'] != 'Y') & (data_2_env['Wet Spell'] != 'N')]
print(invalid_rows)

    Year        Location  Avg Min Temp *C  Yr Rain mm Heat Wave Dry Spell  \
22  2005  East Carloston             21.9     1669.74         N         N
56  2016  East Carloston             23.1     2042.77         N         N

   Cold Wave Wet Spell
22         N         1
56         N         y

In [25]:
#replacing with 'Y' Or 'N'
data_2_env['Wet Spell'] = data_2_env['Wet Spell'].replace({'1':'Y','y':'Y'})

In [26]:
#checking again for 'Wet Spell' column
invalid_rows = data_2_env[(data_2_env['Wet Spell'] != 'Y') & (data_2_env['Wet Spell'] != 'N')]
print(invalid_rows)

Empty DataFrame
Columns: [Year, Location, Avg Min Temp *C, Yr Rain mm, Heat Wave, Dry Spell, Cold Wave, Wet Spell]
Index: []

In [27]:
#moving on to third datafile
data_3_crop = pd.read_csv('data_3_crop.csv')
data_3_crop

,Year,Location,Irrigation,Crop Type,Crop Damage,Yield,Observer
0,1980.0,East Carlburgh,Y,Canola,1.0,902.41,Sheila Vasquez
1,NaN,Ramirezview,Y,NaN,1.0,1737.23,Veronica Hernandez
2,1980.0,Ramirezview,Y,Wheat,1.0,1737.23,Veronica Hernandez
3,1980.0,East Carloston,N,Wheat,0.0,1498.37,Derek King
4,1981.0,East Carlburgh,Y,Wheat,1.0,1612.48,Sheila Vasquez
...,...,...,...,...,...,...,...
120,2018.0,East Carlburgh,Y,Maize,0.0,1388.00,Ashley Lopez
121,2018.0,East Carloston,N,Maize,1.0,1180.34,Linda Mendoza
122,2019.0,East Carloston,N,Canola,1.0,768.50,Sarah Simpson
123,2019.0,East Carlburgh,Y,Canola,0.0,994.37,Cindy Orr
124,2019.0,Ramirezview,Y,Wheat,0.0,1771.76,Samantha Baker

In [28]:
# checking for duplicate rows
duplicate_rows = data_3_crop[data_3_crop.duplicated()]
print(duplicate_rows)

# handling the duplicate rows
data_3_crop = data_3_crop.drop_duplicates()

# checking if duplicate rows have been handled
duplicate_rows_after = data_3_crop[data_3_crop.duplicated()]
print(duplicate_rows_after)

       Year     Location Irrigation Crop Type  Crop Damage    Yield  \
110  2015.0  Ramirezview          Y     Wheat          0.0  1774.11

       Observer
110  John Meyer
Empty DataFrame
Columns: [Year, Location, Irrigation, Crop Type, Crop Damage, Yield, Observer]
Index: []

In [29]:
# Find the rows with missing values
missing_values = data_3_crop[data_3_crop.isnull().any(axis=1)]

# Print the rows with missing values
print(missing_values)

       Year        Location Irrigation Crop Type  Crop Damage    Yield  \
1       NaN     Ramirezview          Y       NaN          1.0  1737.23
88   2008.0  East Carlburgh        NaN    Canola          0.0   969.27
94   2010.0  East Carloston          N    Canola          NaN   782.33
104  2013.0             NaN          Y    Canola          0.0      NaN

               Observer
1    Veronica Hernandez
88        Melissa Boyle
94                  NaN
104       Lee Gutierrez

In [30]:
# checking the row if it matches with another row and the subset difference is year and crop type columns 
duplicated_rows = data_3_crop[data_3_crop.duplicated(subset=data_3_crop.columns.difference(['Year','Crop Type']), keep=False)]

# Print the duplicated rows
print(duplicated_rows)

     Year     Location Irrigation Crop Type  Crop Damage    Yield  \
1     NaN  Ramirezview          Y       NaN          1.0  1737.23
2  1980.0  Ramirezview          Y     Wheat          1.0  1737.23

             Observer
1  Veronica Hernandez
2  Veronica Hernandez

In [31]:
# Find and delete the row where 'year' is missing
row_missing_year = data_3_crop[data_3_crop['Year'].isnull()]
print("Row with missing 'year' column:")
print(row_missing_year)

data_3_crop = data_3_crop.dropna(subset=['Year'])
#deleted row

Row with missing 'year' column:
   Year     Location Irrigation Crop Type  Crop Damage    Yield  \
1   NaN  Ramirezview          Y       NaN          1.0  1737.23

             Observer
1  Veronica Hernandez

In [32]:
# finding row where irrigation column is missing and corresponding row similar to it
duplicated_rows = data_3_crop[data_3_crop.duplicated(subset=data_3_crop.columns.difference(['Irrigation']), keep=False)]

# Print the duplicated rows
print(duplicated_rows)
###Irrigation missing handling

      Year        Location Irrigation Crop Type  Crop Damage   Yield  \
87  2008.0  East Carlburgh          Y    Canola          0.0  969.27
88  2008.0  East Carlburgh        NaN    Canola          0.0  969.27

         Observer
87  Melissa Boyle
88  Melissa Boyle

In [33]:
# checking rows with missing values in 'irrigation' column
missing_irrigation_rows = data_3_crop[data_3_crop['Irrigation'].isna()]

# handling rows with missing values in 'irrigation' column
data_3_crop = data_3_crop.dropna(subset=['Irrigation'])

# get the deleted rows
deleted_rows = missing_irrigation_rows.copy()

In [34]:
# checking the rows which do not match the criteria
invalid_rows = data_3_crop[(data_3_crop['Irrigation'] != 'Y') & (data_3_crop['Irrigation'] != 'N')]
print(invalid_rows)

data_3_crop['Irrigation'] = data_3_crop['Irrigation'].replace({'No': 'N'})
##irrigation column handled

      Year        Location Irrigation Crop Type  Crop Damage   Yield  \
73  2004.0  East Carloston         No    Canola          0.0  786.32

           Observer
73  Stephen Collins

In [35]:
#check the values in irrigation column
invalid_rows = data_3_crop[(data_3_crop['Irrigation'] != 'Y') & (data_3_crop['Irrigation'] != 'N')]
print(invalid_rows)

Empty DataFrame
Columns: [Year, Location, Irrigation, Crop Type, Crop Damage, Yield, Observer]
Index: []

In [36]:
# finding row where crop damage and observer are missing and corresponding similar row with subset difference of crop damage and observer
duplicated_rows = data_3_crop[data_3_crop.duplicated(subset=data_3_crop.columns.difference(['Crop Damage','Observer']), keep=False)]

# Print the duplicated rows
print(duplicated_rows)
##handling of missing values: crop damage and observer

      Year        Location Irrigation Crop Type  Crop Damage   Yield  \
93  2010.0  East Carloston          N    Canola          0.0  782.33
94  2010.0  East Carloston          N    Canola          NaN  782.33

         Observer
93  Michelle Pena
94            NaN

In [37]:
# checking rows with missing values in column crop damage
missing_irrigation_rows = data_3_crop[data_3_crop['Crop Damage'].isna()]

# Remove rows with missing values
data_3_crop = data_3_crop.dropna(subset=['Crop Damage'])

# get the deleted rows
deleted_rows = missing_irrigation_rows.copy()

In [38]:
# checking if handled 
duplicated_rows = data_3_crop[data_3_crop.duplicated(subset=data_3_crop.columns.difference(['Crop Damage','Observer']), keep=False)]

# Print the duplicated rows
print(duplicated_rows)
##handled missing values: crop damagae and observer

Empty DataFrame
Columns: [Year, Location, Irrigation, Crop Type, Crop Damage, Yield, Observer]
Index: []

In [39]:
# finding rows with missing yield and location and corresponding row similar to it.
duplicated_rows = data_3_crop[data_3_crop.duplicated(subset=data_3_crop.columns.difference(['Yield','Location']), keep=False)]

# Print the duplicated rows
print(duplicated_rows)
##handling of missing values: yield and location

       Year     Location Irrigation Crop Type  Crop Damage    Yield  \
103  2013.0  Ramirezview          Y    Canola          0.0  1066.84
104  2013.0          NaN          Y    Canola          0.0      NaN

          Observer
103  Lee Gutierrez
104  Lee Gutierrez

In [40]:
# handling the missing values
missing_irrigation_rows = data_3_crop[data_3_crop['Yield'].isna()]

# Remove rows with missing values
data_3_crop = data_3_crop.dropna(subset=['Yield'])

# get the deleted rows
deleted_rows = missing_irrigation_rows.copy()

In [41]:
#checking if handled
duplicated_rows = data_3_crop[data_3_crop.duplicated(subset=data_3_crop.columns.difference(['Yield','Location']), keep=False)]

# Print the duplicated rows
print(duplicated_rows)
##handled missing values: yield and location

Empty DataFrame
Columns: [Year, Location, Irrigation, Crop Type, Crop Damage, Yield, Observer]
Index: []

In [42]:
# replacing 0.0 with 'N' and 1.0 with 'Y' in 'crop damage' column
data_3_crop['Crop Damage'] = data_3_crop['Crop Damage'].replace({0.0: 'N', 1.0: 'Y'})
data_3_crop

,Year,Location,Irrigation,Crop Type,Crop Damage,Yield,Observer
0,1980.0,East Carlburgh,Y,Canola,Y,902.41,Sheila Vasquez
2,1980.0,Ramirezview,Y,Wheat,Y,1737.23,Veronica Hernandez
3,1980.0,East Carloston,N,Wheat,N,1498.37,Derek King
4,1981.0,East Carlburgh,Y,Wheat,Y,1612.48,Sheila Vasquez
5,1981.0,Ramirezview,Y,Maize,Y,1422.37,Rebecca Rivas
...,...,...,...,...,...,...,...
120,2018.0,East Carlburgh,Y,Maize,N,1388.00,Ashley Lopez
121,2018.0,East Carloston,N,Maize,Y,1180.34,Linda Mendoza
122,2019.0,East Carloston,N,Canola,Y,768.50,Sarah Simpson
123,2019.0,East Carlburgh,Y,Canola,N,994.37,Cindy Orr
124,2019.0,Ramirezview,Y,Wheat,N,1771.76,Samantha Baker

In [43]:
invalid_rows = data_3_crop[(data_3_crop['Crop Damage'] != 'Y') & (data_3_crop['Crop Damage'] != 'N')]
print(invalid_rows)

Empty DataFrame
Columns: [Year, Location, Irrigation, Crop Type, Crop Damage, Yield, Observer]
Index: []

In [44]:
# Get rows with missing values
rows_with_missing_values = data_3_crop[data_3_crop.isnull().any(axis=1)]
print(rows_with_missing_values)

# Delete rows with missing values
data_3_crop = data_3_crop.drop(rows_with_missing_values.index)

# Reset the index
data_3_crop = data_3_crop.reset_index(drop=True)

Empty DataFrame
Columns: [Year, Location, Irrigation, Crop Type, Crop Damage, Yield, Observer]
Index: []

In [45]:
duplicate_rows = data_3_crop[data_3_crop.duplicated()]
print(duplicate_rows)
#no more duplicate rows or rows with missing values

Empty DataFrame
Columns: [Year, Location, Irrigation, Crop Type, Crop Damage, Yield, Observer]
Index: []

In [46]:
#### merging of files-
desired_columns = ["Year", "Location", "Heat Wave", "Dry Spell", "Cold Wave", "Wet Spell", "Avg Min Temp °C", "Yr Rain mm"]

# Reindex the columns in both data frames
data_1_env = data_1_env.reindex(columns=desired_columns)
data_2_env = data_2_env.reindex(columns=desired_columns)

# Concatenate the data frames vertically
merged_data = pd.concat([data_1_env, data_2_env])

# Reset the index of the merged data frame
merged_data = merged_data.reset_index(drop=True)

merged_data

,Year,Location,Heat Wave,Dry Spell,Cold Wave,Wet Spell,Avg Min Temp °C,Yr Rain mm
0,1980,East Carlburgh,N,N,Y,N,19.9,880.31066
1,1980,Ramirezview,N,N,Y,N,23.4,794.00146
2,1980,East Carloston,N,N,N,N,20.7,1089.66000
3,1981,East Carlburgh,N,N,Y,N,20.1,789.53106
4,1981,Ramirezview,N,N,Y,N,22.9,682.08144
...,...,...,...,...,...,...,...,...
115,2018,East Carlburgh,Y,N,N,Y,NaN,1695.80000
116,2018,East Carloston,N,N,N,Y,NaN,1842.32000
117,2019,East Carloston,N,N,N,Y,NaN,1904.86000
118,2019,East Carlburgh,Y,N,N,Y,NaN,1570.74000
119,2019,Ramirezview,Y,N,N,Y,NaN,1166.17000

In [47]:
# Defining the common columns to merge on
common_columns = ["Year", "Location"]

# Merge data_3_crop with the previously merged data frame(1,2)
merged_data = merged_data.merge(data_3_crop, on=common_columns)

merged_data

,Year,Location,Heat Wave,Dry Spell,Cold Wave,Wet Spell,Avg Min Temp °C,Yr Rain mm,Irrigation,Crop Type,Crop Damage,Yield,Observer
0,1980,East Carlburgh,N,N,Y,N,19.9,880.31066,Y,Canola,Y,902.41,Sheila Vasquez
1,1980,Ramirezview,N,N,Y,N,23.4,794.00146,Y,Wheat,Y,1737.23,Veronica Hernandez
2,1980,East Carloston,N,N,N,N,20.7,1089.66000,N,Wheat,N,1498.37,Derek King
3,1981,East Carlburgh,N,N,Y,N,20.1,789.53106,Y,Wheat,Y,1612.48,Sheila Vasquez
4,1981,Ramirezview,N,N,Y,N,22.9,682.08144,Y,Maize,Y,1422.37,Rebecca Rivas
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2018,East Carlburgh,Y,N,N,Y,NaN,1695.80000,Y,Maize,N,1388.00,Ashley Lopez
116,2018,East Carloston,N,N,N,Y,NaN,1842.32000,N,Maize,Y,1180.34,Linda Mendoza
117,2019,East Carloston,N,N,N,Y,NaN,1904.86000,N,Canola,Y,768.50,Sarah Simpson
118,2019,East Carlburgh,Y,N,N,Y,NaN,1570.74000,Y,Canola,N,994.37,Cindy Orr
119,2019,Ramirezview,Y,N,N,Y,NaN,1166.17000,Y,Wheat,N,1771.76,Samantha Baker

In [48]:
duplicate_rows = merged_data.duplicated()
num_duplicates = duplicate_rows.sum()

print("Number of duplicated rows:", num_duplicates)

Number of duplicated rows: 0

In [49]:
merged_data["Avg Min Temp °C"] = merged_data["Avg Min Temp °C"].round(2)
merged_data
#rounding of the decimal places for cleaner code

,Year,Location,Heat Wave,Dry Spell,Cold Wave,Wet Spell,Avg Min Temp °C,Yr Rain mm,Irrigation,Crop Type,Crop Damage,Yield,Observer
0,1980,East Carlburgh,N,N,Y,N,19.9,880.31066,Y,Canola,Y,902.41,Sheila Vasquez
1,1980,Ramirezview,N,N,Y,N,23.4,794.00146,Y,Wheat,Y,1737.23,Veronica Hernandez
2,1980,East Carloston,N,N,N,N,20.7,1089.66000,N,Wheat,N,1498.37,Derek King
3,1981,East Carlburgh,N,N,Y,N,20.1,789.53106,Y,Wheat,Y,1612.48,Sheila Vasquez
4,1981,Ramirezview,N,N,Y,N,22.9,682.08144,Y,Maize,Y,1422.37,Rebecca Rivas
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2018,East Carlburgh,Y,N,N,Y,NaN,1695.80000,Y,Maize,N,1388.00,Ashley Lopez
116,2018,East Carloston,N,N,N,Y,NaN,1842.32000,N,Maize,Y,1180.34,Linda Mendoza
117,2019,East Carloston,N,N,N,Y,NaN,1904.86000,N,Canola,Y,768.50,Sarah Simpson
118,2019,East Carlburgh,Y,N,N,Y,NaN,1570.74000,Y,Canola,N,994.37,Cindy Orr
119,2019,Ramirezview,Y,N,N,Y,NaN,1166.17000,Y,Wheat,N,1771.76,Samantha Baker

In [50]:
#rounding of decimal places for cleaner code
merged_data["Yr Rain mm"] = merged_data["Yr Rain mm"].round(2)
merged_data

,Year,Location,Heat Wave,Dry Spell,Cold Wave,Wet Spell,Avg Min Temp °C,Yr Rain mm,Irrigation,Crop Type,Crop Damage,Yield,Observer
0,1980,East Carlburgh,N,N,Y,N,19.9,880.31,Y,Canola,Y,902.41,Sheila Vasquez
1,1980,Ramirezview,N,N,Y,N,23.4,794.00,Y,Wheat,Y,1737.23,Veronica Hernandez
2,1980,East Carloston,N,N,N,N,20.7,1089.66,N,Wheat,N,1498.37,Derek King
3,1981,East Carlburgh,N,N,Y,N,20.1,789.53,Y,Wheat,Y,1612.48,Sheila Vasquez
4,1981,Ramirezview,N,N,Y,N,22.9,682.08,Y,Maize,Y,1422.37,Rebecca Rivas
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2018,East Carlburgh,Y,N,N,Y,NaN,1695.80,Y,Maize,N,1388.00,Ashley Lopez
116,2018,East Carloston,N,N,N,Y,NaN,1842.32,N,Maize,Y,1180.34,Linda Mendoza
117,2019,East Carloston,N,N,N,Y,NaN,1904.86,N,Canola,Y,768.50,Sarah Simpson
118,2019,East Carlburgh,Y,N,N,Y,NaN,1570.74,Y,Canola,N,994.37,Cindy Orr
119,2019,Ramirezview,Y,N,N,Y,NaN,1166.17,Y,Wheat,N,1771.76,Samantha Baker

In [51]:
#check unique observers,locations,crop types
unique_locations = merged_data['Location'].unique()
print(unique_locations)

unique_observer = merged_data['Observer'].unique()
print(unique_observer)

unique_crop = merged_data['Crop Type'].unique()
print(unique_crop)

['East Carlburgh' 'Ramirezview' 'East Carloston']
['Sheila Vasquez' 'Veronica Hernandez' 'Derek King' 'Rebecca Rivas'
 'Linda Anderson' 'Lori Garcia' 'Samantha Ramsey' 'Michelle Garcia MD'
 'Erin Ramirez' 'Joanna Palmer' 'David Rodriguez' 'Miguel Martin'
 'Mark Mendez' 'John Young' 'Martin Richards' 'David Garcia'
 'Janet Galloway' 'Robert Keith' 'Leslie Williams' 'Rachel Martinez'
 'Evan Mckay' 'Emily Johnson' 'Laura Lewis' 'Anthony Blackburn'
 'Kelly Thomas' 'Ronnie Morrow' 'Stephen Collins' 'Mallory James'
 'Amanda Sanchez' 'Emily Mccoy' 'Nicole Marks' 'Robert Oneal'
 'Pamela Williams' 'Franklin Graham' 'Justin Gibbs' 'Kristi Brewer'
 'Melissa Boyle' 'Lee Gutierrez' 'Michelle Pena' 'Samantha Parker'
 'Kenneth Jackson' 'Joshua Hopkins' 'Lindsay Jennings' 'John Meyer'
 'Regina Alexander' 'Ashley Lopez' 'Joshua Duncan' 'Samantha Baker'
 'Linda Mendoza' 'Sarah Simpson' 'Cindy Orr']
['Canola' 'Wheat' 'Maize']

In [52]:
merged_data.to_csv('clean_data.csv', index=False)

In [53]:
#clean_csv file created